#!/usr/bin/env bash
set -e

_thisdir="$( cd "$( dirname "$0" )" && pwd )"
_build="${_thisdir}/_build"
_date=$(date +'%Y%m%d')
_version="${_date}"
_newmsysbase="${_build}/newmsys"
_newmsys="${_newmsysbase}/msys64"
_pkgname="msys2"

create_chroot_system() {
  echo "[Creating chroot system...]"
  rm -Rf "${_newmsysbase}" && mkdir -p "${_newmsys}"

  pushd "${_newmsys}" > /dev/null
    mkdir -p var/lib/pacman
    mkdir -p var/log
    mkdir -p tmp

    pacman -Syu --root "${_newmsys}"
    pacman -S filesystem msys2-runtime --noconfirm --root "${_newmsys}"
    pacman -S base --noconfirm --root "${_newmsys}"
    . "${_thisdir}/install-application"
  popd > /dev/null
}

create_sfx() {
  echo "[Creating SFX...]"
  "${_thisdir}/create-sfx.sh" "${_newmsys}" "${_thisdir}/${_pkgname}-${_date}.sfx.exe"
}

create_win_appimg() {
  echo "[Creating WinAppImg...]"
  "${_thisdir}/create-win-appimg.sh" "${_newmsys}" "${_thisdir}/${_pkgname}-${_date}.win-appimg.exe"
}

main() {
  pacman -S --noconfirm --needed curl unzip dos2unix "${MINGW_PACKAGE_PREFIX}"-{git,7zip}

  create_chroot_system
  create_sfx
  create_win_appimg
}

main