name: Build Installer

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-installer:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - msystem: UCRT64
            arch_name: x86_64
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: setup-msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true

      - name: Build Installer
        shell: msys2 {0}
        run: |
          bash make-msys2-installer

      - name: Set Release Env
        id: set_env
        shell: msys2 {0}
        run: |
          if [[ "$GITHUB_REF" == 'refs/heads/main' ]] || [[ "$GITHUB_REF" == 'refs/tags/weekly' ]]; then
            echo 'RELEASE_TAG=weekly' >> "$GITHUB_OUTPUT"
            echo 'FILE_NAME=latest' >> "$GITHUB_OUTPUT"
          elif [[ "$GITHUB_REF_TYPE" == 'tag' ]]; then
            echo "RELEASE_TAG=${GITHUB_REF_NAME//\//-}" >> "$GITHUB_OUTPUT"
            echo "FILE_NAME=${GITHUB_REF_NAME//\//-}" >> "$GITHUB_OUTPUT"
          else
            echo "RELEASE_TAG=" >> "$GITHUB_OUTPUT"
            echo "FILE_NAME=${GITHUB_REF//\//-}" >> "$GITHUB_OUTPUT"
          fi

      - name: Rename Artifacts and Checksums
        if: steps.set_env.outputs.RELEASE_TAG != ''
        env:
          FILE_NAME: ${{ steps.set_env.outputs.FILE_NAME }}
        run: |
          mv Yunzai-*.sfx.exe "Yunzai-$env:FILE_NAME.sfx.exe"
          mv Yunzai-*.win-appimg.exe "Yunzai-$env:FILE_NAME.win-appimg.exe"
          sha512sum.exe Yunzai-* | tee.exe Yunzai-sha512sum.txt

      - name: Upload Results
        uses: actions/upload-artifact@v7
        with:
          name: Yunzai-${{ steps.set_env.outputs.FILE_NAME }}
          path: Yunzai-*

      - name: Upload to Release
        if: steps.set_env.outputs.RELEASE_TAG != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ steps.set_env.outputs.RELEASE_TAG }}
        run: |
          gh release upload "$env:TAG_NAME" Yunzai-* --clobber || `
          gh release create "$env:TAG_NAME" Yunzai-* --title "$env:TAG_NAME"
